from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/ui/donations_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Donations(object):
    def setupUi(self, Donations):
        Donations.setObjectName("Donations")
        Donations.resize(400, 300)

        self.retranslateUi(Donations)
        QtCore.QMetaObject.connectSlotsByName(Donations)

    def retranslateUi(self, Donations):
        
        Donations.setWindowTitle(_("Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Donations = QtWidgets.QWidget()
    ui = Ui_Donations()
    ui.setupUi(Donations)
    Donations.show()
    sys.exit(app.exec())
