from gettext import gettext as _
# Form implementation generated from reading ui file './zapzap/view/ui/personalization_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Personalization(object):
    def setupUi(self, Personalization):
        Personalization.setObjectName("Personalization")
        Personalization.resize(400, 300)

        self.retranslateUi(Personalization)
        QtCore.QMetaObject.connectSlotsByName(Personalization)

    def retranslateUi(self, Personalization):
        
        Personalization.setWindowTitle(_("Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Personalization = QtWidgets.QWidget()
    ui = Ui_Personalization()
    ui.setupUi(Personalization)
    Personalization.show()
    sys.exit(app.exec())
